apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
  labels:
    app: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - name: pipeline
        image: lostlegend2702/pipeline:4.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-service
spec:
  selector:
    app: pipeline
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
